COPY (

SELECT RIAGENDR as GENDER,
       category_description AS CATEGORY,
       COUNT(*) as COUNT
FROM DEMO_G
INNER JOIN DR1IFF_G ON DEMO_G.SEQN = DR1IFF_G.SEQN
INNER JOIN WWEIA1112_foodcat_FNDDS ON WWEIA1112_foodcat_FNDDS.food_code = DR1IFF_G.DR1IFDCD
WHERE RIAGENDR IS NOT NULL
GROUP BY GENDER, CATEGORY
ORDER BY CATEGORY ASC, GENDER ASC;

) TO STDOUT WITH CSV HEADER;
